apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-egjb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vdjd-tenant/rhtap-demo-app/hacbs-test-project-egjb@sha256:6bc43570a74b506646ee14b5f7ad75137519a233765e06894b5757acb8878c15
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
